package svg

import (
	"bytes"
	"math/rand"
	"testing"

	"github.com/chandler37/gobackgammon/brd"
	"github.com/chandler37/gobackgammon/svg"
)

var gold = `<?xml version="1.0"?>
<!-- Generated by SVGo -->
<svg width="240" height="240"
     xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">
<rect x="0" y="0" width="240" height="240" style="fill:aqua" />
<line x1="0" y1="0" x2="0" y2="239" style="stroke-width:2;stroke:black" />
<line x1="0" y1="0" x2="239" y2="0" style="stroke-width:2;stroke:black" />
<line x1="239" y1="0" x2="239" y2="239" style="stroke-width:2;stroke:black" />
<line x1="0" y1="239" x2="239" y2="239" style="stroke-width:2;stroke:black" />
<polyline points="28,237 34,143 40,237" style="fill:palegoldenrod; stroke-width:2;stroke:palegoldenrod" />
<circle cx="34" cy="233" r="5" style="fill:white" />
<circle cx="34" cy="220" r="5" style="fill:white" />
<circle cx="34" cy="207" r="5" style="fill:white" />
<circle cx="34" cy="193" r="5" style="fill:white" />
<circle cx="34" cy="180" r="5" style="fill:white" />
<polyline points="41,237 47,143 53,237" style="fill:indigo; stroke-width:2;stroke:indigo" />
<polyline points="54,237 60,143 66,237" style="fill:palegoldenrod; stroke-width:2;stroke:palegoldenrod" />
<polyline points="67,237 73,143 79,237" style="fill:indigo; stroke-width:2;stroke:indigo" />
<polyline points="80,237 86,143 92,237" style="fill:palegoldenrod; stroke-width:2;stroke:palegoldenrod" />
<circle cx="86" cy="233" r="5" style="fill:red" />
<circle cx="86" cy="220" r="5" style="fill:red" />
<circle cx="86" cy="207" r="5" style="fill:red" />
<polyline points="93,237 99,143 105,237" style="fill:indigo; stroke-width:2;stroke:indigo" />
<polyline points="133,237 139,143 145,237" style="fill:palegoldenrod; stroke-width:2;stroke:palegoldenrod" />
<circle cx="139" cy="233" r="5" style="fill:red" />
<circle cx="139" cy="220" r="5" style="fill:red" />
<circle cx="139" cy="207" r="5" style="fill:red" />
<circle cx="139" cy="193" r="5" style="fill:red" />
<circle cx="139" cy="180" r="5" style="fill:red" />
<polyline points="146,237 152,143 158,237" style="fill:indigo; stroke-width:2;stroke:indigo" />
<polyline points="159,237 165,143 171,237" style="fill:palegoldenrod; stroke-width:2;stroke:palegoldenrod" />
<polyline points="172,237 178,143 184,237" style="fill:indigo; stroke-width:2;stroke:indigo" />
<polyline points="185,237 191,143 197,237" style="fill:palegoldenrod; stroke-width:2;stroke:palegoldenrod" />
<polyline points="198,237 204,143 210,237" style="fill:indigo; stroke-width:2;stroke:indigo" />
<circle cx="204" cy="233" r="5" style="fill:white" />
<circle cx="204" cy="220" r="5" style="fill:white" />
<polyline points="28,2 34,96 40,2" style="fill:indigo; stroke-width:2;stroke:indigo" />
<circle cx="34" cy="7" r="5" style="fill:red" />
<circle cx="34" cy="20" r="5" style="fill:red" />
<circle cx="34" cy="33" r="5" style="fill:red" />
<circle cx="34" cy="47" r="5" style="fill:red" />
<circle cx="34" cy="60" r="5" style="fill:red" />
<polyline points="41,2 47,96 53,2" style="fill:palegoldenrod; stroke-width:2;stroke:palegoldenrod" />
<polyline points="54,2 60,96 66,2" style="fill:indigo; stroke-width:2;stroke:indigo" />
<polyline points="67,2 73,96 79,2" style="fill:palegoldenrod; stroke-width:2;stroke:palegoldenrod" />
<polyline points="80,2 86,96 92,2" style="fill:indigo; stroke-width:2;stroke:indigo" />
<circle cx="86" cy="7" r="5" style="fill:white" />
<circle cx="86" cy="20" r="5" style="fill:white" />
<circle cx="86" cy="33" r="5" style="fill:white" />
<polyline points="93,2 99,96 105,2" style="fill:palegoldenrod; stroke-width:2;stroke:palegoldenrod" />
<polyline points="133,2 139,96 145,2" style="fill:indigo; stroke-width:2;stroke:indigo" />
<circle cx="139" cy="7" r="5" style="fill:white" />
<circle cx="139" cy="20" r="5" style="fill:white" />
<circle cx="139" cy="33" r="5" style="fill:white" />
<circle cx="139" cy="47" r="5" style="fill:white" />
<circle cx="139" cy="60" r="5" style="fill:white" />
<polyline points="146,2 152,96 158,2" style="fill:palegoldenrod; stroke-width:2;stroke:palegoldenrod" />
<polyline points="159,2 165,96 171,2" style="fill:indigo; stroke-width:2;stroke:indigo" />
<polyline points="172,2 178,96 184,2" style="fill:palegoldenrod; stroke-width:2;stroke:palegoldenrod" />
<polyline points="185,2 191,96 197,2" style="fill:indigo; stroke-width:2;stroke:indigo" />
<polyline points="198,2 204,96 210,2" style="fill:palegoldenrod; stroke-width:2;stroke:palegoldenrod" />
<circle cx="204" cy="7" r="5" style="fill:red" />
<circle cx="204" cy="20" r="5" style="fill:red" />
<rect x="112" y="2" width="13" height="236" style="fill:chartreuse" />
<rect x="2" y="114" width="13" height="13" style="fill:white" />
<text x="8" y="125" style="text-anchor:middle;font-size:16px;fill:black" >1</text>
<text x="83" y="120" style="text-anchor:middle;font-size:20px;fill:white" >6</text>
<text x="92" y="120" style="text-anchor:middle;font-size:20px;fill:white" >4</text>
</svg>
`

func TestBoard(t *testing.T) {
	rand.Seed(37)
	b := brd.New(true)
	var buf bytes.Buffer
	svg.Board(240, b, New(&buf))
	if x := buf.String(); x != gold {
		t.Errorf("x=%v", x)
	}
}
